version: '3'

services:
  # MongoDB service
  mongo:
    image: mongo
    container_name: my-mongo
    ports:
      - '27018:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DATABASE}

  # Next.js app service
  app:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - mongo
    environment:
      NODE_ENV: ${NODE_ENV}
      MONGODB_URI: ${MONGO_URI}
    #COMMAND: [ "pm2-runtime", "start", "npm", "--", "start" ]

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app
